version: 2
updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
