language: csharp
sudo: false
dist: trusty
mono: none
dotnet: 6.0

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
 - dotnet restore
 - dotnet test
 - dotnet publish
